# CS231n L3 Loss function and optimization
* TODO :    
    1. Define a *loss function* that quantifies our unhappiness with the scores across the trainning data
    2. Come up with a way of efficiently finding the parameters that minimize the loss function(*optimization*)

## Loss functions
* Given a dataset of examples $\{(x_{i}, y_{i})\}^{N}_{i=1}$. Where $x_i$ is image and $y_i$ is integer label
* Loss over the dataset is a sum of loss over examples :
    $ L = \frac{1}{N}\sum_i{L_i(f(x_i,W),y_i)}$


## optimization


In [46]:
# Load dataset
from tensorflow.keras.datasets import cifar10
import matplotlib.pyplot as plt
import numpy as np

(x_train, y_train),(x_test, y_test) = cifar10.load_data()
image_width = x_train.shape[1]
image_height = x_train.shape[2]

print("Trainning data : ")
print("Number of examples : {}".format(x_train.shape[0]))
print("Number of channels : {}".format(x_train.shape[3]))
print("Image size : {} X {}".format(x_train.shape[1], x_train.shape[2]))
print("")
print("Test data : ")
print("Number of examples : {}".format(x_test.shape[0]))
print("Number of channels : {}".format(x_test.shape[3]))
print("Image size : {} X {}".format(x_test.shape[1], x_test.shape[2]))

print
print(y_train)
print(y_train.shape)
plt.figure(figsize=(3,3))
for i in range(10):
    index = np.where(y_train[:,0] == i)
    plt.subplot(int("33"+str(i+1)))
    plt.imshow(x_train[index[0][0],:,:,:])
# plt.show()


Trainning data : 
Number of examples : 50000
Number of channels : 3
Image size : 32 X 32

Test data : 
Number of examples : 10000
Number of channels : 3
Image size : 32 X 32
[[6]
 [9]
 [9]
 ...
 [9]
 [1]
 [1]]
(50000, 1)
0
(array([   29,    30,    35, ..., 49941, 49992, 49994], dtype=int64),)
1
(array([    4,     5,    32, ..., 49993, 49998, 49999], dtype=int64),)
2
(array([    6,    13,    18, ..., 49987, 49991, 49995], dtype=int64),)
3
(array([    9,    17,    21, ..., 49979, 49982, 49983], dtype=int64),)
4
(array([    3,    10,    20, ..., 49981, 49984, 49990], dtype=int64),)
5
(array([   27,    40,    51, ..., 49964, 49980, 49988], dtype=int64),)
6
(array([    0,    19,    22, ..., 49962, 49966, 49996], dtype=int64),)
7
(array([    7,    11,    12, ..., 49965, 49978, 49986], dtype=int64),)
8
(array([    8,    62,    69, ..., 49968, 49976, 49985], dtype=int64),)
9
(array([    1,     2,    14, ..., 49963, 49971, 49997], dtype=int64),)


ValueError: Single argument to subplot must be a three-digit integer, not 3310

In [2]:
# 3 image example
# cat, car, frog
# f(x, W) = Wx --> score!